// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace Ext1
{
	public class BaseClass
	{
		private int counter;

		public BaseClass() {
			counter = 0;
			System.Console.WriteLine ("BaseClass - ctor");
		}

		public void Done() {
			counter++;
			System.Console.WriteLine ("BaseClass - Done");
		}
	}
}

